# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1107, 852)
        Dialog.setAutoFillBackground(True)
        self.gridLayout_3 = QtGui.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget_RecentFolder = QtGui.QTabWidget(Dialog)
        self.tabWidget_RecentFolder.setAutoFillBackground(True)
        self.tabWidget_RecentFolder.setObjectName(_fromUtf8("tabWidget_RecentFolder"))
        self.tab = QtGui.QWidget()
        self.tab.setAutoFillBackground(True)
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tabWidget_RecentFolder.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setAutoFillBackground(True)
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout = QtGui.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tableWidget_OS = QtGui.QTableWidget(self.tab_2)
        self.tableWidget_OS.setAutoFillBackground(True)
        self.tableWidget_OS.setObjectName(_fromUtf8("tableWidget_OS"))
        self.tableWidget_OS.setColumnCount(10)
        self.tableWidget_OS.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget_OS, 2, 0, 1, 1)
        self.tabWidget_RecentFolder.addTab(self.tab_2, _fromUtf8(""))
        self.tab_Registry = QtGui.QWidget()
        self.tab_Registry.setAutoFillBackground(True)
        self.tab_Registry.setObjectName(_fromUtf8("tab_Registry"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_Registry)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tabWidget_UserAssist = QtGui.QTabWidget(self.tab_Registry)
        self.tabWidget_UserAssist.setAutoFillBackground(True)
        self.tabWidget_UserAssist.setObjectName(_fromUtf8("tabWidget_UserAssist"))
        self.tab_MountedDevices = QtGui.QWidget()
        self.tab_MountedDevices.setAutoFillBackground(True)
        self.tab_MountedDevices.setObjectName(_fromUtf8("tab_MountedDevices"))
        self.tableWidget_MountedDevices = QtGui.QTableWidget(self.tab_MountedDevices)
        self.tableWidget_MountedDevices.setGeometry(QtCore.QRect(1, 1, 1061, 711))
        self.tableWidget_MountedDevices.setAutoFillBackground(True)
        self.tableWidget_MountedDevices.setObjectName(_fromUtf8("tableWidget_MountedDevices"))
        self.tableWidget_MountedDevices.setColumnCount(10)
        self.tableWidget_MountedDevices.setRowCount(0)
        self.tabWidget_UserAssist.addTab(self.tab_MountedDevices, _fromUtf8(""))
        self.tab_OpenSavePidMRU = QtGui.QWidget()
        self.tab_OpenSavePidMRU.setAutoFillBackground(True)
        self.tab_OpenSavePidMRU.setObjectName(_fromUtf8("tab_OpenSavePidMRU"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_OpenSavePidMRU)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tableWidget_OpenSavePidlMRU = QtGui.QTableWidget(self.tab_OpenSavePidMRU)
        self.tableWidget_OpenSavePidlMRU.setObjectName(_fromUtf8("tableWidget_OpenSavePidlMRU"))
        self.tableWidget_OpenSavePidlMRU.setColumnCount(10)
        self.tableWidget_OpenSavePidlMRU.setRowCount(0)
        self.gridLayout_5.addWidget(self.tableWidget_OpenSavePidlMRU, 0, 0, 1, 1)
        self.tabWidget_UserAssist.addTab(self.tab_OpenSavePidMRU, _fromUtf8(""))
        self.tab_TypedPaths = QtGui.QWidget()
        self.tab_TypedPaths.setObjectName(_fromUtf8("tab_TypedPaths"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_TypedPaths)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.tableWidget_TypedPaths = QtGui.QTableWidget(self.tab_TypedPaths)
        self.tableWidget_TypedPaths.setAutoFillBackground(True)
        self.tableWidget_TypedPaths.setObjectName(_fromUtf8("tableWidget_TypedPaths"))
        self.tableWidget_TypedPaths.setColumnCount(10)
        self.tableWidget_TypedPaths.setRowCount(0)
        self.gridLayout_6.addWidget(self.tableWidget_TypedPaths, 0, 0, 1, 1)
        self.tableWidget_TypedPaths.raise_()
        self.tabWidget_UserAssist.addTab(self.tab_TypedPaths, _fromUtf8(""))
        self.tab_UserAssist = QtGui.QWidget()
        self.tab_UserAssist.setAutoFillBackground(True)
        self.tab_UserAssist.setObjectName(_fromUtf8("tab_UserAssist"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_UserAssist)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tableWidget_5 = QtGui.QTableWidget(self.tab_UserAssist)
        self.tableWidget_5.setAutoFillBackground(True)
        self.tableWidget_5.setObjectName(_fromUtf8("tableWidget_5"))
        self.tableWidget_5.setColumnCount(10)
        self.tableWidget_5.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget_5, 0, 0, 1, 1)
        self.tableWidget_5.raise_()
        self.tabWidget_UserAssist.addTab(self.tab_UserAssist, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.tabWidget_UserAssist, 0, 0, 1, 1)
        self.tabWidget_RecentFolder.addTab(self.tab_Registry, _fromUtf8(""))
        self.tab_Jumplists = QtGui.QWidget()
        self.tab_Jumplists.setAutoFillBackground(True)
        self.tab_Jumplists.setObjectName(_fromUtf8("tab_Jumplists"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_Jumplists)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.tableWidget_JumpLists = QtGui.QTableWidget(self.tab_Jumplists)
        self.tableWidget_JumpLists.setAutoFillBackground(True)
        self.tableWidget_JumpLists.setObjectName(_fromUtf8("tableWidget_JumpLists"))
        self.tableWidget_JumpLists.setColumnCount(10)
        self.tableWidget_JumpLists.setRowCount(0)
        self.gridLayout_7.addWidget(self.tableWidget_JumpLists, 0, 0, 1, 1)
        self.tabWidget_RecentFolder.addTab(self.tab_Jumplists, _fromUtf8(""))
        self.tab_Prefetch = QtGui.QWidget()
        self.tab_Prefetch.setAutoFillBackground(True)
        self.tab_Prefetch.setObjectName(_fromUtf8("tab_Prefetch"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_Prefetch)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tableWidget_Prefetch = QtGui.QTableWidget(self.tab_Prefetch)
        self.tableWidget_Prefetch.setAutoFillBackground(True)
        self.tableWidget_Prefetch.setObjectName(_fromUtf8("tableWidget_Prefetch"))
        self.tableWidget_Prefetch.setColumnCount(10)
        self.tableWidget_Prefetch.setRowCount(0)
        self.gridLayout_8.addWidget(self.tableWidget_Prefetch, 0, 0, 1, 1)
        self.tabWidget_RecentFolder.addTab(self.tab_Prefetch, _fromUtf8(""))
        self.tab_RecentFolder = QtGui.QWidget()
        self.tab_RecentFolder.setAutoFillBackground(True)
        self.tab_RecentFolder.setObjectName(_fromUtf8("tab_RecentFolder"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_RecentFolder)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.tableWidget_6 = QtGui.QTableWidget(self.tab_RecentFolder)
        self.tableWidget_6.setObjectName(_fromUtf8("tableWidget_6"))
        self.tableWidget_6.setColumnCount(10)
        self.tableWidget_6.setRowCount(0)
        self.gridLayout_9.addWidget(self.tableWidget_6, 0, 0, 1, 1)
        self.tabWidget_RecentFolder.addTab(self.tab_RecentFolder, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget_RecentFolder, 0, 2, 1, 1)
        self.button_Start_Exam = QtGui.QPushButton(Dialog)
        self.button_Start_Exam.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_Start_Exam.setObjectName(_fromUtf8("button_Start_Exam"))
        self.gridLayout_3.addWidget(self.button_Start_Exam, 1, 0, 1, 1)
        self.button_Exit = QtGui.QPushButton(Dialog)
        self.button_Exit.setObjectName(_fromUtf8("button_Exit"))
        self.gridLayout_3.addWidget(self.button_Exit, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget_RecentFolder.setCurrentIndex(5)
        self.tabWidget_UserAssist.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.tabWidget_RecentFolder.setTabText(self.tabWidget_RecentFolder.indexOf(self.tab), _translate("Dialog", "Start", None))
        self.tabWidget_RecentFolder.setTabText(self.tabWidget_RecentFolder.indexOf(self.tab_2), _translate("Dialog", "Operating System Information", None))
        self.tabWidget_UserAssist.setTabText(self.tabWidget_UserAssist.indexOf(self.tab_MountedDevices), _translate("Dialog", "Mounted Devices", None))
        self.tabWidget_UserAssist.setTabText(self.tabWidget_UserAssist.indexOf(self.tab_OpenSavePidMRU), _translate("Dialog", "OpenSavePidlMRU", None))
        self.tabWidget_UserAssist.setTabText(self.tabWidget_UserAssist.indexOf(self.tab_TypedPaths), _translate("Dialog", "Typed Paths", None))
        self.tabWidget_UserAssist.setTabText(self.tabWidget_UserAssist.indexOf(self.tab_UserAssist), _translate("Dialog", "UserAssist", None))
        self.tabWidget_RecentFolder.setTabText(self.tabWidget_RecentFolder.indexOf(self.tab_Registry), _translate("Dialog", "Registry", None))
        self.tabWidget_RecentFolder.setTabText(self.tabWidget_RecentFolder.indexOf(self.tab_Jumplists), _translate("Dialog", "Jumplists", None))
        self.tabWidget_RecentFolder.setTabText(self.tabWidget_RecentFolder.indexOf(self.tab_Prefetch), _translate("Dialog", "Prefetch", None))
        self.tabWidget_RecentFolder.setTabText(self.tabWidget_RecentFolder.indexOf(self.tab_RecentFolder), _translate("Dialog", "Recent Folder", None))
        self.button_Start_Exam.setText(_translate("Dialog", "Start", None))
        self.button_Exit.setText(_translate("Dialog", "Exit", None))

